In [3]:
import numpy as np
import pandas as pd

In [11]:
data = pd.read_csv("/home/student/Downloads/1.csv")

In [12]:
data

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2020/12/01'    110       130     409.1
1         60  2020/12/02'    117       145     479.0
2         60  2020/12/03'    103       135     340.0
3         45  2020/12/04'    109       175     282.4
4         45  2020/12/05'    117       148     406.0
5         60  2020/12/06'    102       127    -300.0
6         60  2020/12/07'    110       136     374.0
7        450  2020/12/08'    104       134     253.3
8         30  2020/12/09'    109       133     195.1
9         60  2020/12/10'     98       124     269.0
10        60  2020/12/11'    103       147     329.3
11        60  2020/12/12'    100       120     250.7
12        60  2020/12/12'    100       120     250.7
13        60  2020/12/13'    106       128     345.3
14        60  2020/12/14'    104       132     379.3
15        60  2020/12/15'     98       123     275.0
16        60  2020/12/16'     98       120     215.2
17        60  2020/12/17'    100       120     300.0
18        45  2020/12/18'     90       112       NaN
19        60  2020/12/19'    103       123     323.0
20        45  2020/12/20'     97       125     243.0
21        60  2020/12/21'    108       131     364.2
22        45          NaN    100       119     282.0
23        60  2020/12/23'    130       101     300.0
24        45  2020/12/24'    105       132     246.0
25        60  2020/12/25'    102       126     334.5
26        60     20201226    100       120     250.0
27        60  2020/12/27'     92       118     241.0
28        60  2020/12/28'    103       132       NaN
29        60  2020/12/29'    100       132    -280.0
30        60  2020/12/30'    102       129     380.3
31        60  2020/12/31'     92       115     243.0

In [13]:
data.head()

   Duration         Date  Pulse  Maxpulse  Calories
0        60  2020/12/01'    110       130     409.1
1        60  2020/12/02'    117       145     479.0
2        60  2020/12/03'    103       135     340.0
3        45  2020/12/04'    109       175     282.4
4        45  2020/12/05'    117       148     406.0

In [14]:
data.tail()

    Duration         Date  Pulse  Maxpulse  Calories
27        60  2020/12/27'     92       118     241.0
28        60  2020/12/28'    103       132       NaN
29        60  2020/12/29'    100       132    -280.0
30        60  2020/12/30'    102       129     380.3
31        60  2020/12/31'     92       115     243.0

In [15]:
data.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  266.013333
std     70.039591    7.832933   12.998759  164.876415
min     30.000000   90.000000  101.000000 -300.000000
25%     60.000000  100.000000  120.000000  247.000000
50%     60.000000  102.500000  127.500000  282.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [17]:
data.shape

(32, 5)

In [20]:
data.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

<h1>Handling Missing Values</h1>

In [22]:
data.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [23]:
data.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

<h1> Type Casting </h1>

In [30]:

data["Duration"] = data["Duration"].astype(float)

data.dtypes

Duration    float64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [31]:
data["Duration"]

0      60.0
1      60.0
2      60.0
3      45.0
4      45.0
5      60.0
6      60.0
7     450.0
8      30.0
9      60.0
10     60.0
11     60.0
12     60.0
13     60.0
14     60.0
15     60.0
16     60.0
17     60.0
18     45.0
19     60.0
20     45.0
21     60.0
22     45.0
23     60.0
24     45.0
25     60.0
26     60.0
27     60.0
28     60.0
29     60.0
30     60.0
31     60.0
Name: Duration, dtype: float64

<h1> Counting </h1>

In [32]:
data.count()

Duration    32
Date        31
Pulse       32
Maxpulse    32
Calories    30
dtype: int64

<h1> Min & Max </h1>

In [36]:
data["Duration"].min()

30.0

In [37]:
data["Duration"].max()

450.0

<h1> Statistics </h1>

In [38]:
data.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  266.013333
std     70.039591    7.832933   12.998759  164.876415
min     30.000000   90.000000  101.000000 -300.000000
25%     60.000000  100.000000  120.000000  247.000000
50%     60.000000  102.500000  127.500000  282.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

<h1> Dropping Null Values </h1>

In [41]:
data = data.dropna()

In [42]:
data.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [43]:
data

    Duration         Date  Pulse  Maxpulse  Calories
0       60.0  2020/12/01'    110       130     409.1
1       60.0  2020/12/02'    117       145     479.0
2       60.0  2020/12/03'    103       135     340.0
3       45.0  2020/12/04'    109       175     282.4
4       45.0  2020/12/05'    117       148     406.0
5       60.0  2020/12/06'    102       127    -300.0
6       60.0  2020/12/07'    110       136     374.0
7      450.0  2020/12/08'    104       134     253.3
8       30.0  2020/12/09'    109       133     195.1
9       60.0  2020/12/10'     98       124     269.0
10      60.0  2020/12/11'    103       147     329.3
11      60.0  2020/12/12'    100       120     250.7
12      60.0  2020/12/12'    100       120     250.7
13      60.0  2020/12/13'    106       128     345.3
14      60.0  2020/12/14'    104       132     379.3
15      60.0  2020/12/15'     98       123     275.0
16      60.0  2020/12/16'     98       120     215.2
17      60.0  2020/12/17'    100       120     300.0
19      60.0  2020/12/19'    103       123     323.0
20      45.0  2020/12/20'     97       125     243.0
21      60.0  2020/12/21'    108       131     364.2
23      60.0  2020/12/23'    130       101     300.0
24      45.0  2020/12/24'    105       132     246.0
25      60.0  2020/12/25'    102       126     334.5
26      60.0     20201226    100       120     250.0
27      60.0  2020/12/27'     92       118     241.0
29      60.0  2020/12/29'    100       132    -280.0
30      60.0  2020/12/30'    102       129     380.3
31      60.0  2020/12/31'     92       115     243.0

<h1> Sample Dataset Creation</h1>

In [45]:
import pandas as pd

In [51]:
d = {
        "Age" : [21,58,48,20,30,89,65,25],
        "Salary" : [80000,60000,100000,400000,90000,100000,500000,30000],
        "Gender" :["M","F","F","M","M","M","F","F"],
        "MStatus" : [1,0,0,0,0,1,1,1]
}


data2 = pd.DataFrame(d)

data2

   Age  Salary Gender  MStatus
0   21   80000      M        1
1   58   60000      F        0
2   48  100000      F        0
3   20  400000      M        0
4   30   90000      M        0
5   89  100000      M        1
6   65  500000      F        1
7   25   30000      F        1

In [53]:

data2["MStatus"] = data2["MStatus"].astype(bool)

data2.dtypes

Age         int64
Salary      int64
Gender     object
MStatus      bool
dtype: object

In [55]:

data2["Age"] = data2["Age"].astype(float)

data2.dtypes

Age        float64
Salary       int64
Gender      object
MStatus       bool
dtype: object

In [56]:
data2

    Age  Salary Gender  MStatus
0  21.0   80000      M     True
1  58.0   60000      F    False
2  48.0  100000      F    False
3  20.0  400000      M    False
4  30.0   90000      M    False
5  89.0  100000      M     True
6  65.0  500000      F     True
7  25.0   30000      F     True

In [58]:
data2.head(1)

    Age  Salary Gender  MStatus
0  21.0   80000      M     True

In [59]:
data2.loc[0]

Age         21.0
Salary     80000
Gender         M
MStatus     True
Name: 0, dtype: object

In [60]:
data2.iloc[0]

Age         21.0
Salary     80000
Gender         M
MStatus     True
Name: 0, dtype: object